In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [7]:
a1 = a.reshape(2, 6)
a1

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a2 = a.reshape(6, 2)
a2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [11]:
a3 = a.reshape(4, 3)
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [12]:
a4 = a.reshape(3, 4)
a4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [13]:
a5 = a.reshape(12, 1)
a5

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [14]:

a6 = a.reshape(12, -1)
a6

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [16]:
a7 = a.reshape(3, -1)
a7

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
a8 = a.reshape(6, -1)
a8

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [18]:
a9 = a.reshape(-1, 2)
a9

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
a10 = a.reshape(-1, 3)
a10

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным? - нельзя

In [20]:
a5.ndim

2

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [21]:
x = np.random.randn(3, 4)
x

array([[-0.02722203, -2.20879507, -0.22187208, -1.59326844],
       [ 0.44176495, -0.48175844,  0.54402624,  0.06054177],
       [-2.06800107,  0.47246025,  1.18370128,  0.28888104]])

In [22]:
x.size

12

In [27]:
x1 = x.reshape(1, 12)
print(x1, 'размерность', x1.ndim)
x1.size

[[-0.02722203 -2.20879507 -0.22187208 -1.59326844  0.44176495 -0.48175844
   0.54402624  0.06054177 -2.06800107  0.47246025  1.18370128  0.28888104]] размерность 2


12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [36]:
a = np.arange(20, 0, -2)
print('массив a', a, 'форма', a.shape, 'размерность', a.size)

массив a [20 18 16 14 12 10  8  6  4  2] форма (10,) размерность 10


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [37]:
b = np.arange(20, 1, -2)
print('массив b', b, 'форма', b.shape, 'размерность', b.size)

массив b [20 18 16 14 12 10  8  6  4  2] форма (10,) размерность 10


разницы между массивами нет

8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [56]:
a = np.zeros((3, 2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
b = np.ones((2, 2))
b

array([[1., 1.],
       [1., 1.]])

In [58]:
v = np.vstack((a, b))
print(v, 'размерность v', v.size)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]] размерность v 10


9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [59]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [60]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [62]:
B = np.dot(A, At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [63]:
B.size

16

In [65]:
detB = np.linalg.det(B)
detB

0.0

определитель матрицы равен 0, следовательно нельзя вычислить обратную матрицу

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [80]:
np.random.seed(42)

In [81]:
np.random.randint(0, 100, 5)

array([51, 92, 14, 71, 60])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [86]:
c = np.random.randint(0, 16, 16)
c

array([ 2, 11,  6,  3, 15,  8,  2,  4,  2,  6,  4,  8,  6,  1,  3,  8])

12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [87]:
C = c.reshape(4, 4)
C

array([[ 2, 11,  6,  3],
       [15,  8,  2,  4],
       [ 2,  6,  4,  8],
       [ 6,  1,  3,  8]])

In [88]:
D = B + 10*C
D

array([[ 25, 124,  83,  62],
       [164, 130, 106, 162],
       [ 43, 146, 189, 292],
       [ 92, 132, 242, 382]])

In [89]:
detD = np.linalg.det(D)
detD

105207799.99999973

In [90]:
rankD = np.linalg.matrix_rank(D)
rankD

4

In [91]:
invD = np.linalg.inv(D)
invD

array([[ 0.00052715,  0.00566403, -0.01049523,  0.00553495],
       [-0.00215687,  0.00448465,  0.01971831, -0.01662443],
       [ 0.0278103 , -0.01182555, -0.04384371,  0.03401535],
       [-0.01699969,  0.0045778 ,  0.02348932, -0.01451965]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [92]:
invD = np.where(invD < 0, 0, 1)
invD

array([[1, 1, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0]])

In [95]:
print(B)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


In [96]:
print(C)

[[ 2 11  6  3]
 [15  8  2  4]
 [ 2  6  4  8]
 [ 6  1  3  8]]


In [100]:
E = np.where(invD > 0, B, C)
E

array([[  5,  14,   6,  32],
       [ 15,  50,  86,   4],
       [ 23,   6,   4, 212],
       [  6, 122, 212,   8]])